const SEED_RACES = [
  { id: 'r1', round: 1, name: 'Australian Grand Prix', circuit: 'Albert Park', country: 'Australia', flag_emoji: '🇦🇺', date: '2025-03-16', laps: 58, lap_length_km: 5.278, pit_lane_time_loss: 24, drs_zones: 4, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Street-style circuit in Melbourne. Fast and flowing with a mix of high and low speed corners.', typical_strategy: 'One-stop. Medium to Hard most common. Safety car likely.' },
  { id: 'r2', round: 2, name: 'Chinese Grand Prix', circuit: 'Shanghai International Circuit', country: 'China', flag_emoji: '🇨🇳', date: '2025-03-23', laps: 56, lap_length_km: 5.451, pit_lane_time_loss: 28, drs_zones: 2, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Long back straight and a unique snail-shaped final sector. High tyre degradation.', typical_strategy: 'Two-stop. High deg favours early pit.' },
  { id: 'r3', round: 3, name: 'Japanese Grand Prix', circuit: 'Suzuka Circuit', country: 'Japan', flag_emoji: '🇯🇵', date: '2025-04-06', laps: 53, lap_length_km: 5.807, pit_lane_time_loss: 26, drs_zones: 1, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Figure-of-eight layout with the iconic 130R and Spoon curve. Demands high downforce.', typical_strategy: 'One-stop. Hard tyre very durable here.' },
  { id: 'r4', round: 4, name: 'Bahrain Grand Prix', circuit: 'Bahrain International Circuit', country: 'Bahrain', flag_emoji: '🇧🇭', date: '2025-04-13', laps: 57, lap_length_km: 5.412, pit_lane_time_loss: 29, drs_zones: 3, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Desert circuit with heavy tyre wear due to abrasive surface and high temperatures.', typical_strategy: 'Two-stop. Soft-Medium-Hard most common.' },
  { id: 'r5', round: 5, name: 'Saudi Arabian Grand Prix', circuit: 'Jeddah Corniche Circuit', country: 'Saudi Arabia', flag_emoji: '🇸🇦', date: '2025-04-20', laps: 50, lap_length_km: 6.174, pit_lane_time_loss: 25, drs_zones: 3, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Fastest street circuit on the calendar. Very long lap with minimal tyre deg.', typical_strategy: 'One-stop. Undercut is powerful here.' },
  { id: 'r6', round: 6, name: 'Miami Grand Prix', circuit: 'Miami International Autodrome', country: 'USA', flag_emoji: '🇺🇸', date: '2025-05-04', laps: 57, lap_length_km: 5.412, pit_lane_time_loss: 27, drs_zones: 3, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Purpose-built street circuit around Hard Rock Stadium. High safety car probability.', typical_strategy: 'One or two-stop depending on safety car.' },
  { id: 'r7', round: 7, name: 'Emilia Romagna Grand Prix', circuit: 'Autodromo Enzo e Dino Ferrari', country: 'Italy', flag_emoji: '🇮🇹', date: '2025-05-18', laps: 63, lap_length_km: 4.909, pit_lane_time_loss: 25, drs_zones: 2, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Imola — old-school circuit with limited overtaking. Track position is key.', typical_strategy: 'One-stop. Overcut works well here.' },
  { id: 'r8', round: 8, name: 'Monaco Grand Prix', circuit: 'Circuit de Monaco', country: 'Monaco', flag_emoji: '🇲🇨', date: '2025-05-25', laps: 78, lap_length_km: 3.337, pit_lane_time_loss: 29, drs_zones: 1, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'The jewel of the calendar. Impossible to overtake — qualifying and strategy are everything.', typical_strategy: 'One-stop. Track position is everything. Safety car almost guaranteed.' },
  { id: 'r9', round: 9, name: 'Spanish Grand Prix', circuit: 'Circuit de Barcelona-Catalunya', country: 'Spain', flag_emoji: '🇪🇸', date: '2025-06-01', laps: 66, lap_length_km: 4.657, pit_lane_time_loss: 23, drs_zones: 2, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'High-speed circuit with heavy tyre wear. A true test of car balance.', typical_strategy: 'Two-stop. Medium-Hard-Hard most common.' },
  { id: 'r10', round: 10, name: 'Canadian Grand Prix', circuit: 'Circuit Gilles Villeneuve', country: 'Canada', flag_emoji: '🇨🇦', date: '2025-06-15', laps: 70, lap_length_km: 4.361, pit_lane_time_loss: 28, drs_zones: 2, weather_forecast: 'mixed', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Street circuit on Île Notre-Dame. Wall of Champions at the final chicane. Rain common.', typical_strategy: 'One-stop. Safety car very likely — timing it is key.' },
  { id: 'r11', round: 11, name: 'Austrian Grand Prix', circuit: 'Red Bull Ring', country: 'Austria', flag_emoji: '🇦🇹', date: '2025-06-29', laps: 71, lap_length_km: 4.318, pit_lane_time_loss: 22, drs_zones: 3, weather_forecast: 'dry', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Short and punchy circuit in the Styrian mountains. Very high tyre degradation.', typical_strategy: 'Two-stop. Aggressive strategy pays off.' },
  { id: 'r12', round: 12, name: 'British Grand Prix', circuit: 'Silverstone Circuit', country: 'UK', flag_emoji: '🇬🇧', date: '2025-07-06', laps: 52, lap_length_km: 5.891, pit_lane_time_loss: 24, drs_zones: 2, weather_forecast: 'mixed', available_compounds: ['soft', 'medium', 'hard'], track_description: 'Home of British motorsport. High-speed sweepers like Copse and Maggotts-Becketts.', typical_strategy: 'One or two-stop. Weather can change everything.' },
];

export function seedRaces() {
  const existing = localStorage.getItem('pitwall_races');
  if (!existing || JSON.parse(existing).length === 0) {
    localStorage.setItem('pitwall_races', JSON.stringify(SEED_RACES));
  }
}
