import { supabase } from '@/api/supabaseClient';

const SEED_RACES = [
  { id: 'r1',  round: 1,  name: 'Australian Grand Prix',      circuit: 'Albert Park Circuit',              country: 'Australia',   flag_emoji: '🇦🇺', date: '2026-03-08', lat: -37.8497, lon: 144.9680, laps: 58, lap_length_km: 5.278, pit_lane_time_loss: 24, drs_zones: 4, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Street-style circuit in Melbourne. Fast and flowing with a mix of high and low speed corners.', typical_strategy: 'One-stop. Medium to Hard most common. Safety car likely.', actual_results: { winner: 'Max Verstappen', team: 'Red Bull Racing', starting_tire: 'medium', pit_laps: [18, 39], tire_sequence: ['hard'], total_pit_stops: 2, had_safety_car: true, race_completed: true } },
  { id: 'r2',  round: 2,  name: 'Chinese Grand Prix',          circuit: 'Shanghai International Circuit',   country: 'China',       flag_emoji: '🇨🇳', date: '2026-03-15', lat: 31.3389,  lon: 121.2198, laps: 56, lap_length_km: 5.451, pit_lane_time_loss: 28, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Long back straight and a unique snail-shaped final sector. High tyre degradation.', typical_strategy: 'Two-stop. High deg favours early pit.' },
  { id: 'r3',  round: 3,  name: 'Japanese Grand Prix',         circuit: 'Suzuka Circuit',                   country: 'Japan',       flag_emoji: '🇯🇵', date: '2026-03-29', lat: 34.8431,  lon: 136.5407, laps: 53, lap_length_km: 5.807, pit_lane_time_loss: 26, drs_zones: 1, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Figure-of-eight layout with the iconic 130R and Spoon curve. Demands high downforce.', typical_strategy: 'One-stop. Hard tyre very durable here.' },
  { id: 'r4',  round: 4,  name: 'Bahrain Grand Prix',          circuit: 'Bahrain International Circuit',    country: 'Bahrain',     flag_emoji: '🇧🇭', date: '2026-05-02', lat: 26.0325,  lon: 50.5106,  laps: 57, lap_length_km: 5.412, pit_lane_time_loss: 29, drs_zones: 3, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Desert circuit with heavy tyre wear due to abrasive surface and high temperatures.', typical_strategy: 'Two-stop. Soft-Medium-Hard most common.' },
  { id: 'r5',  round: 5,  name: 'Saudi Arabian Grand Prix',    circuit: 'Jeddah Corniche Circuit',          country: 'Saudi Arabia',flag_emoji: '🇸🇦', date: '2026-05-09', lat: 21.6319,  lon: 39.1044,  laps: 50, lap_length_km: 6.174, pit_lane_time_loss: 25, drs_zones: 3, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Fastest street circuit on the calendar. Very long lap with minimal tyre deg.', typical_strategy: 'One-stop. Undercut is powerful here.' },
  { id: 'r6',  round: 6,  name: 'Miami Grand Prix',            circuit: 'Miami International Autodrome',    country: 'USA',         flag_emoji: '🇺🇸', date: '2026-05-10', lat: 25.9581,  lon: -80.2389, laps: 57, lap_length_km: 5.412, pit_lane_time_loss: 27, drs_zones: 3, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Purpose-built street circuit around Hard Rock Stadium. High safety car probability.', typical_strategy: 'One or two-stop depending on safety car.' },
  { id: 'r7',  round: 7,  name: 'Emilia Romagna Grand Prix',   circuit: 'Autodromo Enzo e Dino Ferrari',    country: 'Italy',       flag_emoji: '🇮🇹', date: '2026-05-24', lat: 44.3439,  lon: 11.7167,  laps: 63, lap_length_km: 4.909, pit_lane_time_loss: 25, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Imola — old-school circuit with limited overtaking. Track position is key.', typical_strategy: 'One-stop. Overcut works well here.' },
  { id: 'r8',  round: 8,  name: 'Monaco Grand Prix',           circuit: 'Circuit de Monaco',                country: 'Monaco',      flag_emoji: '🇲🇨', date: '2026-05-31', lat: 43.7347,  lon: 7.4206,   laps: 78, lap_length_km: 3.337, pit_lane_time_loss: 29, drs_zones: 1, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'The jewel of the calendar. Impossible to overtake — qualifying and strategy are everything.', typical_strategy: 'One-stop. Track position is everything. Safety car almost guaranteed.' },
  { id: 'r9',  round: 9,  name: 'Spanish Grand Prix',          circuit: 'Circuit de Barcelona-Catalunya',   country: 'Spain',       flag_emoji: '🇪🇸', date: '2026-06-07', lat: 41.5700,  lon: 2.2611,   laps: 66, lap_length_km: 4.657, pit_lane_time_loss: 23, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'High-speed circuit with heavy tyre wear. A true test of car balance.', typical_strategy: 'Two-stop. Medium-Hard-Hard most common.' },
  { id: 'r10', round: 10, name: 'Canadian Grand Prix',         circuit: 'Circuit Gilles Villeneuve',        country: 'Canada',      flag_emoji: '🇨🇦', date: '2026-06-14', lat: 45.5000,  lon: -73.5228, laps: 70, lap_length_km: 4.361, pit_lane_time_loss: 28, drs_zones: 2, weather_forecast: 'mixed', available_compounds: ['soft','medium','hard'], track_description: 'Street circuit on Île Notre-Dame. Wall of Champions at the final chicane. Rain common.', typical_strategy: 'One-stop. Safety car very likely — timing it is key.' },
  { id: 'r11', round: 11, name: 'Austrian Grand Prix',         circuit: 'Red Bull Ring',                    country: 'Austria',     flag_emoji: '🇦🇹', date: '2026-06-28', lat: 47.2197,  lon: 14.7647,  laps: 71, lap_length_km: 4.318, pit_lane_time_loss: 22, drs_zones: 3, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Short and punchy circuit in the Styrian mountains. Very high tyre degradation.', typical_strategy: 'Two-stop. Aggressive strategy pays off.' },
  { id: 'r12', round: 12, name: 'British Grand Prix',          circuit: 'Silverstone Circuit',              country: 'UK',          flag_emoji: '🇬🇧', date: '2026-07-05', lat: 52.0786,  lon: -1.0169,  laps: 52, lap_length_km: 5.891, pit_lane_time_loss: 24, drs_zones: 2, weather_forecast: 'mixed', available_compounds: ['soft','medium','hard'], track_description: 'Home of British motorsport. High-speed sweepers like Copse and Maggotts-Becketts.', typical_strategy: 'One or two-stop. Weather can change everything.' },
  { id: 'r13', round: 13, name: 'Hungarian Grand Prix',        circuit: 'Hungaroring',                      country: 'Hungary',     flag_emoji: '🇭🇺', date: '2026-07-19', lat: 47.5789,  lon: 19.2486,  laps: 70, lap_length_km: 4.381, pit_lane_time_loss: 27, drs_zones: 1, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Twisty, low-speed circuit. Very hard to overtake. Qualifying crucial.', typical_strategy: 'Two-stop. Soft-Medium-Hard most common.' },
  { id: 'r14', round: 14, name: 'Belgian Grand Prix',          circuit: 'Circuit de Spa-Francorchamps',     country: 'Belgium',     flag_emoji: '🇧🇪', date: '2026-07-26', lat: 50.4372,  lon: 5.9714,   laps: 44, lap_length_km: 7.004, pit_lane_time_loss: 26, drs_zones: 2, weather_forecast: 'mixed', available_compounds: ['soft','medium','hard'], track_description: 'Legendary Ardennes circuit. Eau Rouge, Raidillon, Pouhon. Weather changes in minutes.', typical_strategy: 'One or two-stop. Wet weather very common.' },
  { id: 'r15', round: 15, name: 'Dutch Grand Prix',            circuit: 'Circuit Zandvoort',                country: 'Netherlands', flag_emoji: '🇳🇱', date: '2026-08-30', lat: 52.3888,  lon: 4.5409,   laps: 72, lap_length_km: 4.259, pit_lane_time_loss: 23, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Banked corners and a passionate Dutch crowd. Compact circuit with high tyre wear.', typical_strategy: 'Two-stop. Undercut very effective.' },
  { id: 'r16', round: 16, name: 'Italian Grand Prix',          circuit: 'Autodromo Nazionale Monza',        country: 'Italy',       flag_emoji: '🇮🇹', date: '2026-09-06', lat: 45.6156,  lon: 9.2811,   laps: 53, lap_length_km: 5.793, pit_lane_time_loss: 26, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Temple of Speed. Lowest downforce setup of the year. Slipstream battles everywhere.', typical_strategy: 'One-stop. Hard tyre preferred for long stint.' },
  { id: 'r17', round: 17, name: 'Azerbaijan Grand Prix',       circuit: 'Baku City Circuit',                country: 'Azerbaijan',  flag_emoji: '🇦🇿', date: '2026-09-20', lat: 40.3725,  lon: 49.8533,  laps: 51, lap_length_km: 6.003, pit_lane_time_loss: 30, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Longest straight on the calendar. Narrow old city section. Safety car almost certain.', typical_strategy: 'One-stop. Safety car timing is everything.' },
  { id: 'r18', round: 18, name: 'Singapore Grand Prix',        circuit: 'Marina Bay Street Circuit',        country: 'Singapore',   flag_emoji: '🇸🇬', date: '2026-10-04', lat: 1.2914,   lon: 103.8639, laps: 62, lap_length_km: 5.063, pit_lane_time_loss: 32, drs_zones: 3, weather_forecast: 'mixed', available_compounds: ['soft','medium','hard'], track_description: 'Night race on a bumpy street circuit. Extremely hot and humid. Safety car almost certain.', typical_strategy: 'One-stop. Safety car timing is everything.' },
  { id: 'r19', round: 19, name: 'United States Grand Prix',    circuit: 'Circuit of the Americas',          country: 'USA',         flag_emoji: '🇺🇸', date: '2026-10-18', lat: 30.1328,  lon: -97.6411, laps: 56, lap_length_km: 5.513, pit_lane_time_loss: 25, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Purpose-built circuit with a dramatic uphill Turn 1. High-speed and technical.', typical_strategy: 'Two-stop. High tyre deg on abrasive surface.' },
  { id: 'r20', round: 20, name: 'Mexico City Grand Prix',      circuit: 'Autodromo Hermanos Rodriguez',     country: 'Mexico',      flag_emoji: '🇲🇽', date: '2026-10-25', lat: 19.4042,  lon: -99.0907, laps: 71, lap_length_km: 4.304, pit_lane_time_loss: 24, drs_zones: 3, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'High altitude reduces downforce and engine power. Low tyre deg but tricky braking zones.', typical_strategy: 'One-stop. Tyres last longer at altitude.' },
  { id: 'r21', round: 21, name: 'São Paulo Grand Prix',        circuit: 'Autodromo Jose Carlos Pace',       country: 'Brazil',      flag_emoji: '🇧🇷', date: '2026-11-08', lat: -23.7036, lon: -46.6997, laps: 71, lap_length_km: 4.309, pit_lane_time_loss: 27, drs_zones: 2, weather_forecast: 'mixed', available_compounds: ['soft','medium','hard'], track_description: 'Interlagos — anti-clockwise layout with heavy rain common. Passionate crowd.', typical_strategy: 'Two-stop. Rain can completely change the race.' },
  { id: 'r22', round: 22, name: 'Las Vegas Grand Prix',        circuit: 'Las Vegas Strip Circuit',          country: 'USA',         flag_emoji: '🇺🇸', date: '2026-11-21', lat: 36.1147,  lon: -115.1728, laps: 50, lap_length_km: 6.201, pit_lane_time_loss: 28, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Night race on the famous Strip. Cold temperatures affect tyre warm-up significantly.', typical_strategy: 'Two-stop. Cold track = slow tyre warm-up, soft compound risky.' },
  { id: 'r23', round: 23, name: 'Qatar Grand Prix',            circuit: 'Lusail International Circuit',     country: 'Qatar',       flag_emoji: '🇶🇦', date: '2026-11-29', lat: 25.4900,  lon: 51.4542,  laps: 57, lap_length_km: 5.380, pit_lane_time_loss: 25, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'High-speed flowing circuit under floodlights. Extreme tyre degradation.', typical_strategy: 'Two or three-stop. Tyres degrade very fast.' },
  { id: 'r24', round: 24, name: 'Abu Dhabi Grand Prix',        circuit: 'Yas Marina Circuit',               country: 'UAE',         flag_emoji: '🇦🇪', date: '2026-12-06', lat: 24.4672,  lon: 54.6031,  laps: 58, lap_length_km: 5.281, pit_lane_time_loss: 26, drs_zones: 2, weather_forecast: 'dry',   available_compounds: ['soft','medium','hard'], track_description: 'Season finale. Twilight race transitioning from day to night. Low tyre deg.', typical_strategy: 'One-stop. Track position key in the final sector.' },
];

export async function seedRaces() {
  const { data: existing } = await supabase.from('races').select('id').limit(1);
  if (existing && existing.length > 0) return; // already seeded

  const { error } = await supabase.from('races').upsert(SEED_RACES, { onConflict: 'id' });
  if (error) console.error('Seed error:', error.message);
  else console.log('Races seeded to Supabase ✅');
}
